kind: pipeline
type: kubernetes
name: default

metadata:
  namespace: drone

steps:
  - name: build-docker
    image: plugins/docker
    when:
      branch:
        - main
      event:
        include:
          - push
          - tag
    settings:
      repo: ghcr.io/volcanocookies/ai-pilot-front
      registry: ghcr.io
      tags:
        - latest
      build_args_from_env:
        - DRONE_COMMIT
        - DRONE_BUILD_START
      username: VolcanoCookies
      password:
        from_secret: github-token
