kind: pipeline
type: kubernetes
name: default

metadata:
  namespace: drone

steps:
  - name: build-docker
    image: plugins/docker
    when:
      branch:
        - main
      event:
        include:
          - push
          - tag
    settings:
      repo: ghcr.io/volcanocookies/ai-pilot-front
      registry: ghcr.io
      tags:
        - latest
      build_args_from_env:
        - DRONE_COMMIT
        - DRONE_BUILD_STARTED
      username: VolcanoCookies
      password:
        from_secret: github-token

  - name: deploy
    image: bitnami/kubectl:1.33
    commands:
      - kubectl -n ai-pilot-front rollout restart deploy/ai-pilot-front
      - kubectl -n ai-pilot-front rollout status deploy/ai-pilot-front --timeout=2m
