/*
 * AIPilot Submission Server API
 *
 * API for managing AIPilot submissions and battle matches
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, JsonSchema)]
pub struct AipVersion {
    #[serde(rename = "version")]
    pub version: i32,
    #[serde(rename = "uploadId")]
    pub upload_id: String,
}

impl AipVersion {
    pub fn new(version: i32, upload_id: String) -> AipVersion {
        AipVersion { version, upload_id }
    }
}
