/*
 * AIPilot Submission Server API
 *
 * API for managing AIPilot submissions and battle matches
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StartManualFight200Response {
    #[serde(rename = "matchId", skip_serializing_if = "Option::is_none")]
    pub match_id: Option<uuid::Uuid>,
}

impl StartManualFight200Response {
    pub fn new() -> StartManualFight200Response {
        StartManualFight200Response {
            match_id: None,
        }
    }
}

