/*
 * AIPilot Submission Server API
 *
 * API for managing AIPilot submissions and battle matches
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, JsonSchema)]
pub struct TeamInfo {
    #[serde(rename = "aipId")]
    pub aip_id: uuid::Uuid,
    #[serde(rename = "version")]
    pub version: i32,
}

impl TeamInfo {
    pub fn new(aip_id: uuid::Uuid, version: i32) -> TeamInfo {
        TeamInfo { aip_id, version }
    }
}
