/*
 * AIPilot Submission Server API
 *
 * API for managing AIPilot submissions and battle matches
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UploadAiPilot200Response {
    #[serde(rename = "uploadId")]
    pub upload_id: uuid::Uuid,
    #[serde(rename = "version")]
    pub version: i32,
    #[serde(rename = "aip")]
    pub ai_pilot: models::AiPilot,
}

impl UploadAiPilot200Response {
    pub fn new(
        upload_id: uuid::Uuid,
        version: i32,
        ai_pilot: models::AiPilot,
    ) -> UploadAiPilot200Response {
        UploadAiPilot200Response {
            upload_id,
            version,
            ai_pilot,
        }
    }
}
